### PR TITLE
nfr: update app to use Next.js instead of Vite

### PR DESCRIPTION
**Pull request by ManpreetSL**
Replaced Vite structure with Next.js using create-next-app package.

Issue #6

### CODE REVIEW

**Comment by Harjot1Singh** [comment]
Since you've branched off the Profile branch, you may wish to update this PR target to be thet branch, so that GitHub only shows the diff of what you've done new.

Although, where possible, don't lean into branches of branches of branches too much, to avoid PR dependency pain :)

**Comment by ManpreetSL** [comment]
I've updated the base of this PR to the profile-page branch now, and I'll keep that in mind. Thanks.

**Comment by ManpreetSL** [comment]
Is this okay to merge in? @Harjot1Singh

**Comment by Harjot1Singh** [comment]
Once profile page has merged in, since this is a queued PR!

**Review by Harjot1Singh — APPROVED** [review]
👍🏻 

Not a blocker, but sticking to one style of declaring function components will be more consistent!

**Pull request merged**
